### ISSUE TITLE
Unable to extend the build to use this extension's PDF

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [useblocks/sphinx-simplepdf#57]
I am trying to configure ReadtheDocs to use simplepdf extension as described in your [documentation](https://sphinx-simplepdf.readthedocs.io/en/latest/installation.html).

- I am using version 2 of the .readthedocs.yaml file. But using `build.commands` does not seem to work.  (Error: Property `commands` is not allowed)

As a workaround, I am trying with [builds.jobs](https://docs.readthedocs.io/en/stable/build-customization.html#extend-the-build-process) option. Even this seems to fail on ReadtheDocs during the build with the below trace:

```
Running Sphinx v5.1.1

Configuration error:
config directory doesn't contain a conf.py file (/home/docs/checkouts/readthedocs.org/user_builds/io-amr-ver-demo/checkouts/latest)
```

Can you please help with the right set of configuration options that needs to be written in `.readthedocs.yaml` file.

**Comment by sachin-suresh-rapyuta** [comment]
I also tried to use the same format as mentioned in the documentation:

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

#submodules:
#  include:
#    - paamr-deployment

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  commands:
    - sphinx-build -b simplepdf docs docs/build/simplepdf

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats: all

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

```

I still get the same error.
